services:
  django:
    build:
      context: ./django
    container_name: marg_website
    env_file:
      - ./.env.local
    ports:
      - "8000:8000"
    expose:
      - 8000

  # nginx:
  #   build:
  #     context: ./nginx
  #   container_name: nginx_proxy
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - django
